common: disambiguate ECStatsCollector's set/avg functions
When passing a type that does not match the existing declarations,
the compiler will attempt a conversion, or abort if the conversion is
ambiguous.

x.cpp:5:6: error: call of overloaded ‘f(int)’ is ambiguous
  f(42);
x.cpp:1:6: note: candidate: void f(double)
x.cpp:2:6: note: candidate: void f(long long int)

Rename a few functions so that a long disambiguator like
static_cast<long long>(42) won't be needed.