treewide: replace ECLogger::Log with logf
Fedora 27's standard build flags include -Werror=format-security, and
it erroneously fires on the KC::ECLogger::Log template:

In file included from common/ECLogger.cpp:19:0:
./common/include/kopano/ECLogger.h: In instantiation of "void KC::ECLogger::Log(unsigned int, const char*, T&& ...) [with T = {}]":
common/ECLogger.cpp:1005:107:   required from here
./common/include/kopano/ECLogger.h:187:125: error: format not a string literal and no format arguments [-Werror=format-security]
  template<typename... T> inline void Log(unsigned int level, const char *fmt, T &&...args) { return logf(level, fmt, args...); }

We cannot work around it using -Wno-error (has no effect), so just
replace the Log() call by logf() already, since that was planned
anyway.