build: resolve compile failure due to unqualified identifier milli
main.cpp:251:46: error: 'milli' has not been declared
   duration_cast<milliseconds>(epd).count() % milli::den,

Fixes: kopanocore-8.7.0-114-g877ef9ddb