build: solve ambiguity warning for memory_ptr::operator[]
Solve this weird error reported with bp/8.3.0-718-g6721a6af under gcc
5.4.0:

mapix.cpp: In member function 'virtual HRESULT
 M4LAddrBook::ResolveName(ULONG, ULONG, LPTSTR, LPADRLIST)':
mapix.cpp:2092:13: error: ambiguous overload for 'operator[]'
 (operand types are 'KCHL::memory_ptr<SPropValue>' and 'int')
	lpNewProps[0].ulPropTag = PR_ENTRYID;

What happens here is that p[n] can either mean

1. invocation of memory_ptr::operator[](size_t)
2. invocation of static_cast<T *>(p)[n] followed by
   T::operator[](size_t)

Since memory_ptr::operator[] is coded to have the same behavior as
N°2, drop operator[].