build: fix php5 module build failure
../php-ext/main.h: In destructor 'zvalplus::~zvalplus()':
/usr/include/php5/Zend/zend_variables.h:57:76: error: cannot convert 'zvalplus*'
to 'zval** {aka _zval_struct**}' for argument '1' to 'void _zval_ptr_dtor(zval**)'
 #define zval_ptr_dtor(zval_ptr) _zval_ptr_dtor((zval_ptr) ZEND_FILE_LINE_CC)
../php-ext/main.h:28:16: note: in expansion of macro 'zval_ptr_dtor'
  ~zvalplus() { zval_ptr_dtor(this); }

zval_ptr_dtor has different signatures in php5 and php7. Move
zvalplus is only used for php7. Move it to php7-ext/.