migration-pst: continue in the face of decode errors
We encountered an incorrectly encoded PR_BODY property in the wild,
which would break off folder processing:

UnicodeDecodeError: 'utf16' codec can't decode bytes in position 0-1:
    illegal UTF-16 surrogate

We fix this by decoding the string again, but this time we ignore any
errors, so we just decode the parts which can be decoded.

References: KC-521