backup: better error handling on fatal errors
Instead of printing out an exception like this:

    2017-05-04 14:59:34,019 - backup - INFO - starting backup
    2017-05-04 14:59:34,020 - backup - INFO - starting restore of /home/bo/Desktop/kopano.test
    2017-05-04 14:59:34,033 - backup - INFO - stopping backup
    2017-05-04 14:59:34,034 - backup - ERROR - Traceback (most recent call last):
      File "/home/bo/src/kopano-test/zcp/@/swig/python/kopano/kopano/__init__.py", line 4326, in log_exc
        try: yield
      File "/home/bo/src/kopano-test/zcp/@/swig/python/kopano/kopano/__init__.py", line 4665, in start
        _daemon_helper(self.main, self, self.log)
      File "/home/bo/src/kopano-test/zcp/@/swig/python/kopano/kopano/__init__.py", line 4109, in _daemon_helper
        func()
      File "/home/bo/src/kopanocore/ECtools/backup/kopano_backup/__init__.py", line 195, in main
        self.restore()
      File "/home/bo/src/kopanocore/ECtools/backup/kopano_backup/__init__.py", line 233, in restore
        user = store.user
    AttributeError: 'NoneType' object has no attribute 'user'

We now print a human-readable error in case of e.g. a missing store:

    FATAL ERROR: unable to open store (username: ...)