swig: fixing return value of dict_rows
Since dict_rows returned a list of Property we saw errors like

  TypeError: PT_SYSTIME object does not have 'filetime' attribute

It is supposed to return SPropValue, which this commit fixes.