common: adjust wrong _kc_final tags in ECDebugPrint.h
cov-build reports:
"ECDebugPrint.h", line 154: error #1920: a "final" class type cannot
be used as a base class
  class ECDebugPrint : public ECDebugPrintBase

clang reports:
ECDebugPrint.h:154:29: error: base 'ECDebugPrintBase' is marked 'final'
class ECDebugPrint : public ECDebugPrintBase
ECDebugPrint.h:31:7: note: 'ECDebugPrintBase' declared here
class ECDebugPrintBase _kc_final

But g++ missed this because of
https://build.opensuse.org/request/show/442218 .

References: KC-236