common; workaroud clang libc++ bug w.r.t. strrchr return types
In GNU libc, two strrchr functions are declared when
__CORRECT_ISO_CPP_STRING_H_PROTO is in effect:

	# string.h
	extern "C++"
	{
	extern char *strrchr (char *__s, int __c)
	     throw () __asm ("strrchr") __attribute__ ((__pure__)) __attribute__ ((__nonnull__ (1)));
	extern const char *strrchr (const char *__s, int __c)
	     throw () __asm ("strrchr") __attribute__ ((__pure__)) __attribute__ ((__nonnull__ (1)));
	}
	# cstring
	namespace std {
		using ::strrchr;
	}

That is not the case with clang libc++:

	# string.h
	char *strrchr(const char *, int c);
	# cstring
	namespace std {
		using ::strrchr;
		char *strrchr(char *, int c);
	}

common/UnixUtil.cpp:188:14: error: assigning to "char *" from incompatible
type "const char *"
                progname = argv0;