build: ensure exception includes are present
Debian 7 g++ chokes on HrException.h:

  CXX    ECtools/archiver/ECIterators.lo
In file included from ECtools/archiver/ECIterators.cpp:21:0:
./m4lcommon/HrException.h:26:74: error: expected class-name before '{' token
./m4lcommon/HrException.h: In constructor 'KC::HrException::HrException(HRESULT, const string&)':
./m4lcommon/HrException.h:28:89: error: expected class-name before '(' token
./m4lcommon/HrException.h:28:89: error: expected '{' before '(' token

Go through all files involving "std::exception" or
"std::runtime_error", and see whether (a) <exception> or <stdexcept>
is missing, respectively, and (b) whether such include can be removed
because neither is used.