build: resolve compile error with certain includes
Depending on the set of #includes one has (or has not), g++ may
end up with a build error:

./common/include/kopano/database.hpp:103:27: error: "ECConfig" has
not been declared