client: add a missing &
epclient.cpp: In function MSGServiceEntry
epclient.cpp:620:105: error: invalid cast from type "const GUID"
to type "const MAPIUID*"
   hr = lpAdminProviders->OpenProfileSection(reinterpret_cast
        <const MAPIUID *>(pbGlobalProfileSectionGuid), nullptr,
        MAPI_MODIFY, &~ptrGlobalProfSect);

Fixes: bp/8.4.0-1196-gc7f0a42c