autoconf: make libicu a hard requirement
Some people reported unreadable error messages during compilation:

./.libs/libmapi.so: undefined reference to `KC::ECLocale::operator=(KC::ECLocale const&)'
./.libs/libmapi.so: undefined reference to `KC::ECLocale::ECLocale()'
./.libs/libmapi.so: undefined reference to `KC::ECLocale::~ECLocale()'

This is caused by the absence of libicu (i.e. devel package) so we
improve the usability by adding it has a hard requirement.