build: resolve link failure of kopano-statsd
/usr/bin/ld: ECtools/statsd.o: undefined reference to symbol "_ZN4Json5ValueD1Ev"
/usr/lib/x86_64-linux-gnu/libjsoncpp.so.1: error adding symbols: DSO missing from command line
/usr/bin/ld: ECtools/statsd.o: undefined reference to symbol 'HX_getopt_help_cb@@LIBHX_3.12'
/usr/lib/x86_64-linux-gnu/libHX.so.28: error adding symbols: DSO missing from command line