build: remove constexpr that causes compile errors
clang++ 3.8 is unhappy about constexpr:

./m4lcommon/include/kopano/ECRestriction.h:243:12: error: constexpr
constructor never produces a constant expression
[-Winvalid-constexpr]
        constexpr ECNotRestriction(std::nullptr_t) {}
ECRestriction.h:243:12: note: non-literal type "KC::IRestrictionPush"
cannot be used in a constant expression

References: https://llvm.org/bugs/show_bug.cgi?id=19344