swig: resolve type mismatch error
Apparently it is such that specifying a variable name in the swig *.i
files requires that it exactly matches the C part. What a nasty
pitfall. :-(

Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/KC_Valgrind_Test/workspace/kopano-test/@/test", line 522, in <module>
    testrun.run()
  File "/var/lib/jenkins/jobs/KC_Valgrind_Test/workspace/kopano-test/@/test", line 410, in run
    testrig.run()
  File "/var/lib/jenkins/jobs/KC_Valgrind_Test/workspace/kopano-test/@/test", line 356, in run
    self.config.setup()
  File "/var/lib/jenkins/jobs/KC_Valgrind_Test/workspace/kopano-test/@/test", line 275, in setup
    HookSyncLog(self.path + '/synclog_' + self.name + '.log')
  File "/var/lib/jenkins/jobs/KC_Valgrind_Test/workspace/kopano-test/@/test", line 45, in HookSyncLog
    ECSyncLog.SetLogger(Logger(path))
TypeError: in method 'ECSyncLog_SetLogger', argument 1 of type 'ECLogger *'