build: support gsoap-2.8.30 autogenerated constructors
Because gsoap 2.8.30 implicitly adds constructors to the structs
declared in proto.h when writing out soapStub.h, the classic plain data
brace initialization

provider/libserver/ECSessionGroup.cpp:417:
	notifySyncState syncState = {0, ulChangeId};

is no longer functional without changes. The error emitted is:

ECABObjectTable.cpp: In constructor 'ECABObjectTable::ECABObjectTable(ECSession*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, const ECLocale&)':
ECABObjectTable.cpp:109:2: error: could not convert '{((65529u << 16) | 31u), EC_TABLE_SORT_ASCEND}' from '<brace-enclosed initializer list>' to 'sortOrder'
  };
ECABObjectTable.cpp:114:2: error: could not convert '{sObjectType, ((sizeof (sObjectType) / sizeof ((*(sortOrder*)(& sObjectType)))) + 0ul)}' from '<brace-enclosed initializer list>' to 'sortOrderArray'
  };

The prototypes of soap_id_lookup and soap_id_forward also changed, so
adjust for the new ones. However, KC built with gsoap 2.8.30 fails
massively on tests for some stupid whacko reason.