pyko: fix exception for unknown User attribute
Fix exception for unknown User attribute. Currently, an expression
like 'user.unknown_attribute' leads to an exception talking about
stores (because of our fallback to user.store):

AttributeError: 'Store' object has no attribute 'unknown_attribute'

So we fix this by raising a new AttributeError, replacing 'Store'
with 'User'.