build: add missing climits include
This build failure was observed on an RH7 system.

common/ECLogger.cpp: In member function "unsigned int KC::ECLogger::AddRef()":
common/ECLogger.cpp:137:19: error: "UINT_MAX" was not declared in this scope
  assert(m_ulRef < UINT_MAX);