common: added missing constexpr
When compiling using gcc 4.8 the following error message occured due
to missing constexpr:

    In file included from common/ECACL.cpp:18:0:
    ./common/include/kopano/platform.h:132:83: error: redeclaration 'const IID& KC::iid_of() [with T = IUnknown; IID = GUID]' differs in 'constexpr'
     #define IID_OF(T) namespace KC { template<> inline constexpr const IID &iid_of<T>() { return IID_ ## T; } }
                                                                                   ^
    ./mapi4linux/include/mapidefs.h:674:1: note: in expansion of macro 'IID_OF'
     IID_OF(IUnknown);
     ^
    ./common/include/kopano/platform.h:124:33: error: from previous declaration 'const IID& KC::iid_of() [with T = IUnknown; IID = GUID]'
     template<typename T> const IID &iid_of();