build: resolve link failure showing on Debian 9
/usr/bin/ld: provider/server/ECThreadManager.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line

ECThreadManager.cpp uses pthread functions, but the binary is not
linking in -lpthread, so it rightfully fails.