pkyo: handle notif.object being None
When an update arrives for an item who's folder is gone an exception is
thrown as type_ is being requested on a NoneType object. This fixes:
AttributeError: 'NoneType' object has no attribute 'type_'