build: resolve build failures on g++ 4.7
Debian 7's g++ 4.7 does not implement member function ref qualifiers
(this only came in 4.8.1) as used since commit bp/8.3.0-43-g1e8c92d,
nor does it support alignas (also 4.8). Work around it.

ECRestriction.h:93:51: error: expected ';' at end of member declaration
mapix.cpp:2793:38: error: invalid application of 'sizeof' to incomplete
type 'MAPIAllocateBuffer(ULONG, void**)::mapibuf_head'