swig: added missing include for KCHL::memory_ptr
Build got broken with the following error message:

    libcommon_wrap.cxx: In function 'PyObject* _wrap_DelFavoriteFolder(PyObject*, PyObject*)':
    libcommon_wrap.cxx:4340:3: error: 'KCHL' has not been declared
       KCHL::memory_ptr< std::remove_const< std::remove_pointer< LPSPropValue >::type >::type > tmp2 ;
    ...