build: add -lpthread for dagent
/usr/bin/ld: spooler/DAgent.o: undefined reference to symbol "pthread_create@@GLIBC_2.2.5"
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status