build: fix build failure with libintl
If the GNU gettext implementation of gettext functions is used
instead of the GNU libc implementation of gettext functions, there is
a link error.

This is because INTL_LIBS stays empty when it should not.

/usr/x86_64-alpine-linux-musl/bin/ld: .libs/libkcutil.so:
undefined reference to "libintl_bind_textdomain_codeset"
undefined reference to "libintl_dcgettext"

References: KF-3361