build: drop unnecessary "const" to soothe clang
clang bemoans:
In file included from provider/libserver/cmdutil.cpp:18:
In file included from ./common/include/kopano/platform.h:66:
In file included from ./common/include/kopano/platform.linux.h:26:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/6/../../../../include/c++/6/vector:60:
/usr/bin/../lib64/gcc/x86_64-suse-linux/6/../../../../include/c++/6/bits/stl_algobase.h:294:18: error: no viable
      conversion from 'const SOURCEKEY' to 'typename set<basic_string<char>, less<basic_string<char> >,
      allocator<basic_string<char> > >::value_type' (aka 'std::basic_string<char>')
            *__result = *__first;
                        ^~~~~~~~

This is likely because clang does not try to do double dispatch(?),
cf. https://stackoverflow.com/questions/33632584/ .

As for ECICS.h, drop the "const", the result is not const, so do not
pretend it would be.