libserver: cure compile error on ILP32
On x86-32, gcc aborts:

ECCacheManager.cpp:103:92: error: invalid cast from type "long
unsigned int" to type "size_t {aka unsigned int}"
 m_CellCache.SetMaxSize(std::max(size_t(1 << 30), reinterpret_cast<size_t>(s.totalram / 4)));

std::max needs both arguments to be of the exact same type.
In addition, conversion of s.totalram to size_t may incur an undesired
truncation which is to be avoided.

Fixes: kopanocore-8.6.80-159-g8eb5154d