build: fix build error w.r.t. gettimeofday
Cherry-pick commit kopanocore-8.4.4-1-ga90503c66 .

ECIndexer must have relied on some implicit include; it causes
a build error in the current openSUSE TW.

ECIndexer.cpp:366:2: error: 'gettimeofday' was not declared in this scope
   gettimeofday(&tstart, NULL);