build: resolve ECChannel case of goto across variable iniialization
Debian 8 build reports:

../common/ECChannel.cpp: In static member function "static HRESULT KC::ECChannel::HrSetCtx(KC::ECConfig*)":
../common/ECChannel.cpp:362:1: error: jump to label "exit" [-fpermissive]
 exit:
 ^~~~
../common/ECChannel.cpp:173:9: note:   from here
    goto exit;
         ^~~~
../common/ECChannel.cpp:245:22: note:   crosses initialization of "long int ssl_opclear"
  long ssl_opset = 0, ssl_opclear = 0;

(cherry picked from commit aa6a67bc758a4707de7754e3ecd6f72f4644e4f3)