build: add missing clock_LIBS for RHEL6
clock_gettime was traditionally in -lrt, and only is in -lc for
newer glibc.

 CXXLD mapialloctime
tests/mapialloctime.cpp:61: undefined reference to "clock_gettime"