rest: fix missing shbang line
The file fails to specify the proper interpreter, which breaks RPM builds

+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Bytecompiling .py files below /home/abuild/rpmbuild/BUILDROOT/kopano-8.6.91.0-25.1.x86_64/usr/lib/debug/usr/lib64/python3.6 using /usr/bin/python3.6
Bytecompiling .py files below /home/abuild/rpmbuild/BUILDROOT/kopano-8.6.91.0-25.1.x86_64/usr/lib/debug/usr/lib64/python2.7 using /usr/bin/python2.7
Bytecompiling .py files below /home/abuild/rpmbuild/BUILDROOT/kopano-8.6.91.0-25.1.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
Bytecompiling .py files below /home/abuild/rpmbuild/BUILDROOT/kopano-8.6.91.0-25.1.x86_64/usr/lib/python3.6 using /usr/bin/python3.6
Bytecompiling .py files below /home/abuild/rpmbuild/BUILDROOT/kopano-8.6.91.0-25.1.x86_64/usr/lib64/python2.7 using /usr/bin/python2.7
Bytecompiling .py files below /home/abuild/rpmbuild/BUILDROOT/kopano-8.6.91.0-25.1.x86_64/usr/lib64/python3.6 using /usr/bin/python3.6
/home/abuild/rpmbuild/BUILDROOT/kopano-8.6.91.0-25.1.x86_64/usr/share/kopano-spooler/python/zunit.py
/home/abuild/rpmbuild/BUILDROOT/kopano-8.6.91.0-25.1.x86_64/usr/libexec/kopano/kopano-mfr.py
DEPRECATION WARNING: python2 invoked with /usr/bin/python.
    Use /usr/bin/python3 or /usr/bin/python2
    /usr/bin/python will be removed or switched to Python 3 in the future.
    If you cannot make the switch now, please follow instructions at https://fedoraproject.org/wiki/Changes/Avoid_usr_bin_python_in_RPM_Build#Quick_Opt-Out
Compiling /home/abuild/rpmbuild/BUILDROOT/kopano-8.6.91.0-25.1.x86_64/usr/libexec/kopano/kopano-mfr.py ...
  File "/usr/libexec/kopano/kopano-mfr.py", line 74
    print('Kopano-mfr is already running..', file=sys.stderr)
                                                 ^
SyntaxError: invalid syntax